name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 pytest
    - name: Format with black
      run: black . --line-length 80
    - name: Lint with flake8
      run: flake8 .
    - name: Run unit tests
      run: pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ lower(github.event.repository.name) }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ lower(github.event.repository.name) }}:${{ github.sha }}
        build-args: |
          GITHUB_SHA=${{ github.sha }}
          GITHUB_REF=${{ github.ref }}
      env:
        REPO_NAME_LOWERCASE: ${{ lower(github.event.repository.name) }}